const ADD_NUMBER = 'ADD_NUMBER';
const SUB_NUMBER = 'SUB_NUMBER';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';

module.exports = {
  ADD_NUMBER,
  SUB_NUMBER,
  INCREMENT,
  DECREMENT
}